### PR TITLE
Test dispatch - hosttest macros addition, plus timeout

### PR DESCRIPTION
**Pull request by 0xc0170**
```
mbedgt -V --target frdm-k64f-gcc results:
+---------------+---------------+-----------------------------+--------+--------------------+-------------+
| target        | platform_name | test                        | result | elapsed_time (sec) | copy_method |
+---------------+---------------+-----------------------------+--------+--------------------+-------------+
| frdm-k64f-gcc | K64F          | minar-test-complex_dispatch | OK     | 30.8               | shell       |
| frdm-k64f-gcc | K64F          | minar-test-dispatchtest     | OK     | 15.6               | shell       |
+---------------+---------------+-----------------------------+--------+--------------------+-------------+
```

@bogdanm @PrzemekWirkus

### CODE REVIEW

**Comment by bogdanm** [comment]
OK for now I guess, but in the future we really need to have tests that can run outside mbedgt (not necessarily automated, that is). For example, I used this particular test as a visual confirmation of the K64F MINAR timer implementation correctness.That involved letting it run for a few days and checking that it still blinks. It's not possible to do that anymore.

**Comment by 0xc0170** [comment]
Yes, I did the same when porting tickets to minar for instance. Similar problem we had with spi test when compiling only for one platform.

Adding @PrzemekWirkus to be aware of this. We could create an issue for this somewhere, mbed greentea?

**Comment by bogdanm** [comment]
I don't think this is a greentea issue. After all, greentea tests what you tell it to test, so you shouldn't tell it to test this particular test (also, how many times can one say "test" in a single phrase? Test. There you go. Also, test).

**Comment by 0xc0170** [comment]
I was not saying it's greentea issue. We need to track this somewhere, continue discussion there , not here in minar.

Reference: #10 (tracking issue for this fix)

**Comment by PrzemekWirkus** [comment]
@bogdanm 
>_OK for now I guess, but in the future we really need to have tests that can run outside mbedgt (not necessarily automated, that is)._

* All test can run outside greentea, if they are automated of not. Greentea just runs them one by one and calls proper host test if necessary.
* This porting is done so Greentea can capture test case results and prepare report for CI system.

Bogdan, let's do not mix functional, non-functional and other tests here. Greentea lets you automate subset of unit and functional test cases on hardware.

> _I used this particular test as a visual confirmation of the K64F MINAR timer implementation correctness.That involved letting it run for a few days and checking that it still blinks. It's not possible to do that anymore._

This is code in ```\test``` directory so we assume it is callable with ```yt test``` and ```mbedgt```.
Maybe separate directory for ```examples``` would be better?

**Comment by bogdanm** [comment]
> Bogdan, let's do not mix functional, non-functional and other tests here.

But this is precisely what we're doing. We're implictly assuming that all the tests in `tests/` are created equal. That might not be the case. A (hopefully) better example: I need to test the accuracy of my MINAR timer, so I have a test that'll run for 6 hours, and at the end of the test `mbedgt` will check if the time reported by the test corresponds to the real time. This is a perfectly valid test, but it's not something you'd run as part of a nightly build&test cycle. We need a way to differentiate between different types of tests.

**Comment by 0xc0170** [comment]
@bogdanm FYI, I am not allowed to merge this.

**Pull request merged**
