### PR TITLE
Module - bump drivers version

### PR DESCRIPTION
**Pull request by 0xc0170**

### CODE REVIEW

**Comment by 0xc0170** [comment]
People are reporting "does not meet spec.."

@bogdanm @autopulated

**Comment by autopulated** [comment]
is this dependency necessary any more – Isn't everything minar needs in mbed-util now?

**Comment by 0xc0170** [comment]
@autopulated I believe it's not yet ready. There're pull requests moving Event, FunctionPointer . Once that's merge, I'll look at this to remove this circular dep.

**Comment by autopulated** [comment]
Merging this for now to resolve the error. We can remove the dependency later once #3, and any related changes are merged.

**Pull request merged**
