### PR TITLE
Correct timeIsInPeriod() to correctly handle the 'S==T==E' case

### PR DESCRIPTION
**Pull request by betzw**
Returns true if 'time' is in the range ['start', 'end'], where
all the range may wrap around to zero ('end' may be less than 'start')

Note: the range includes 'end' now!

### CODE REVIEW

**Comment by betzw** [comment]
Fixes issue #41

**Comment by 0xc0170** [comment]
cc @marcuschangarm @autopulated

**Comment by autopulated** [comment]
The previous version returned true for (s=e, t > s, t > e), which would only be correct if scheduling for +0 time was disallowed, and scheduling for +0x100 (where the time mask is 0xff) was allowed: but I don't think that's the case, so this seems right.

I don't think there'd be any bad side effects to admitting s<e, t=e, where the previous version didn't, but either case (B) should also be changed to make it consistent, or we shouldn't change that:

``` C++
           (time < start && end < start && end >= time)){  // (B)
                                                ^ NB
```

**Comment by betzw** [comment]
Agreed! I will update the PR.

**Comment by autopulated** [comment]
:+1:

**Comment by betzw** [comment]
#deadbeef

**Pull request closed without merging**
