### PR TITLE
Updated dependency on major 1 of greentea-client

### PR DESCRIPTION
**Pull request by bogdanm**

### CODE REVIEW

**Comment by bogdanm** [comment]
Major version 1 of greentea-client might not be published yet, but this change is backwards compatible.
The intention is to release a new *minor* version of this module once this PR is merged.
@0xc0170 @bremoran

**Comment by 0xc0170** [comment]
Ah why travis fails then ? I did not see this failure for core-util...

**Comment by bogdanm** [comment]
Because Travis doesn't see the corresponding change in `utest` (https://github.com/ARMmbed/utest/pull/15). Unfortunately this will keep on happening until we merge everything we need to merge.

**Comment by bogdanm** [comment]
> I did not see this failure for core-util...

It depends on which version of `greentea-client` yotta installs. If it installs the old 0.x.y, then all dependencies will be satisfied. If it install 1.0.0, the old `greentea-client:~0.x.y` will fail. Which version of `greentea-client` is actually installed depends on the time when `yotta` first finds a dependency on `greentea-client`, so the results will vary between modules.

**Comment by 0xc0170** [comment]
+1

I was not aware client is already v1.x.x

**Comment by bogdanm** [comment]
Yeah, @PrzemekWirkus is really fast :)

**Pull request merged**
