### PR TITLE
Add a documentation line to define the default tolerance

### LINKED ISSUE #28: Default callback tolerance is 50ms
When a callback is created without specifying a tolerance, the tolerance defaults to the "magic value" of 50ms:

https://github.com/ARMmbed/minar/blob/master/source/minar.cpp#L150

This isn't something most people would expect and it can break their scheduling mechanisms in some cases. We need to decide how we handle this:

- is it OK to have a non-zero default tolerance (which is something most people won't expect)?
- if so, what should be the value of the default tolerance?
- if the default tolerance won't be 0 in the end, this needs to be documented in big bold letters.

### PR DESCRIPTION
**Pull request by bremoran**
cc @bogdanm @autopulated 
Fixes #28

### CODE REVIEW

**Comment by 0xc0170** [comment]
LGTM

**Comment by bremoran** [comment]
@bogdanm @autopulated Review/merge please

**Comment by bogdanm** [comment]
I imagined something a bit more verbose, but this'd work too. +1.

**Comment by bogdanm** [comment]
Yup, precisely like that!

**Pull request merged**
